### ISSUE TITLE
how to track user views of different screens in app

### ISSUE THREAD

**Issue by ajonno** [idehub/react-native-google-analytics-bridge#122]
Sorry if this seems like a dumb question but I just want to double check something - if we want to know which screens in our app a user has opened during a given session - do we need to add ```tracker1.trackScreenView('Home');``` , ```tracker1.trackScreenView('About');``` , ```tracker1.trackScreenView('Settings');```  in each screens/views (RN) component  ?

OR

can we place a single API call eg. in our App root and this API will then send an analytic event each time a user opens a different screen/view ?

**Comment by mcabs3** [comment]
you have to call the trackScreenView anytime you are telling GA the user switched screens. There are many ways to go about it, you could put the event in your componentDidMount, you could have a wrapper around your call to navigate to the screen and have it dynamic in there, etc.

**Comment by cbrevik** [comment]
Hi @ajonno 

As @mcabs3 says, there are many ways of going about it. The implementation details of which is up to you, since every app is different.

To add on to his answer, if you are using any sort of navigation API, there is typically a callback event available on navigation. For the React Native `Navigator` API you for example have [`onDidFocus`](https://facebook.github.io/react-native/docs/navigator.html#ondidfocus). Tracking screens there is also a nice general way to go about it.

**Comment by ajonno** [comment]
hi guys, thanks very much appreciate it !
