### ISSUE TITLE
[Android] Could not invoke native module method

### ISSUE THREAD

**Issue by ryankask** [idehub/react-native-google-analytics-bridge#130]
I upgraded an app to React Native 0.43 and I'm getting the following error when calling a method on a tracker object on Android:

"Could not invoke GoogleAnalyticsBridge.setAppName"

`setAppName()` is just the first method I call -- it happens with all methods. 

I had upgraded the package to version 5 but downgrading back to v4 didn't fix the issue.

I'm curious if any other Android users are experiencing this issue or if it's something related to my setup. Nothing around the analytics code has changed and iOS works fine.

**Comment by cbrevik** [comment]
Hi @ryankask, 9/10 times this is because either you've not implemented it correctly ([see simple example from README](https://github.com/idehub/react-native-google-analytics-bridge#why-a-native-bridge-why-not-use-just-javascript)), or it has not been installed & linked the library correctly (see [manual installation](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation) for extra details).

**Comment by ryankask** [comment]
Thanks for getting back to me, @cbrevik. I had the following in an app's build.gradle and removing it resolved the issue:

```
compile('com.google.android.gms:play-services-analytics:9.4.0') {
    force = true
}
```
