### ISSUE TITLE
[Android] Cannot send decimal values

### ISSUE THREAD

**Issue by Minishlink** [idehub/react-native-google-analytics-bridge#142]
Hi, I wanted to send an event with a decimal value. It works well on iOS but crashes on Android with the error message `TypeError: expected dynamic type 'int64', but had type 'double'`.

It seems to be linked to the `trackEvent` function that [gets an int from the "value"](https://github.com/idehub/react-native-google-analytics-bridge/blob/master/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleAnalyticsBridge.java#L87). Shouldn't it be able to get a `double` value?

**Comment by cbrevik** [comment]
Hi @Minishlink. According to the Android docs, the `value`'s type is `long`, which is an integer type: https://developers.google.com/analytics/devguides/collection/android/v4/events

For iOS it is `NSNumber`, which supports decimal. So that's why it works on that platform: https://developers.google.com/analytics/devguides/collection/ios/v3/events

The platforms sadly differs in some ways, and this is one of them.

**Comment by Minishlink** [comment]
Nice, thanks for the information! :)

I ended up rounding the value so that it's consistent. It might be good to inform the users in the readme.
