### ISSUE TITLE
App timing through Tag Manager broken on Android

### ISSUE THREAD

**Issue by aeirola** [idehub/react-native-google-analytics-bridge#143]
I've used this nice library for tracking events and exceptions through Tag Manager in our application for quite some time now, and today wanted to extend the tracking to include some app timings as well. Everything worked smoothly on iOS, but on Android the hits just wouldn't stick in Google Analytics.

If I push the event with some code similar to:

```javascript
tagManagerPromise.then(() => GoogleTagManager
  .pushDataLayerEvent({
    event: 'timing',
    category: 'Performance',
    var: 'appStartupJS',
    value: 265,
  }));
```

and checking the logs, I see the event being sent off as 

```
06-16 14:45:58.212  2998  3444 D GAv4    : Hit delivery requested: ... t=timing, utc=Performance, utt=265.0, utv=appStartupJS, v=1
```

At first glance, everything seems to be in order. But after some digging I realised that the `utt` parameter needs to be sent off as an integer, as according to the specifications at https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#utt.

Apparently, what seems to be happening, is that the JavaScript `number` type is converted to some kind of floating point number in the React Native NativeModule bridge. I suppose this value is blindly passed through the Google Tag Manager data layer to whatever library then converts the value to a string for sending over to Google Analytics.

The easy fix for this is to just pass the number as a string to the data layer and everything will be OK. Of course this is probably not an obvious solution to most people.

I'm not really sure what would be the appropriate place to fix this issue. I understand why React Native chooses to convert JavaScript number to floating points, and I understand why any values are passed directly through to the Tag Manager data layer. One could argue that the Tag Manager should convert any floating point values to integers before sending them off to Google Analytics. Regardless, I think it is valuable to report it here, since it mainly affects React Native users.

**Comment by cbrevik** [comment]
Hi @aeirola.

Well, the reason for why it's converted to a floating point number is quite simple, but might require a bit of explanation.

First off, you're probably aware of this, but JavaScript does not really have "integers" as such. All JS `number`s are always stored as a floating point number. So even if you define a variable as `var a = 1`, internally it is stored as `1.0`.

So that's the first part to remember. The second thing is that the `pushDataLayerEvent` uses a helper class internally to this library to convert the object that you send in, to a `HashMap` which the GTM-library can push. Since we cannot already know the shape of the object you send in, we have to assume certain things.

So what this helper class assumes, is that [all numbers are floating point](https://github.com/idehub/react-native-google-analytics-bridge/blob/5365c854377dff4f41706b0911f52c77d601dc8c/android/src/main/java/com/idehub/GoogleAnalyticsBridge/ConvertReadableToMap.java#L32). If we converted them to integer by default, it might lead to loss of precision for others who need floating numbers.

What might need to happen, is that we handle conversion of the "timing" `event` object [differently here](https://github.com/idehub/react-native-google-analytics-bridge/blob/5365c854377dff4f41706b0911f52c77d601dc8c/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleTagManagerBridge.java#L102). Check by `event` name or something. I'll have to think a bit on this. PRs/discussion would be welcome as well.

**Comment by aeirola** [comment]
Hello, thanks for the clarifications.

Unfortunately I don't think it makes sense to treat a `timing` event object any differently, since the name of the event is completely dependant on the specific Google Tag Manager configuration a project might use. Thus, any project who chooses to name timing events as `appTiming` or similar, will still run into problems.

Looking through the Google Analytics Measurement Protocol [reference documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters), it seems like there is no floating point type parameters in the API. Of course the Google Tag Manager can be used to send events to other services as well, which might have use for floating point values. But maybe it could be valuable to have some kind of configuration option to choose the number conversion data type, along with some documentation to guide the user to a sensible choice.

It is starting to feel like the proper place to fix this would be Google Tag Manger, since it is the actual client of the API requiring the passed value to be an integer. Unfortunately, I'm not confident that Google is maintaining the old Tag Manager now that they are pushing for using Firebase Analytics in mobile applications.

**Comment by cbrevik** [comment]
Aha, I haven't really used the availability of pushing events through GTM, so excuse my ignorance in that regard.

In that case, maybe a configuration-mapping would do the trick. An Android-only implementation (since iOS can handle both cases) where from the JS we also push a configuration-object/dictionary `pushDataLayerEvent(dictionary = {}, mappingConfig = {})`.

Where `mappingConfig` is something like propertyName (from `dictionary`) -> conversionType:
```javascript
{
    value: 'integer',
    anotherValue, 'float'
}
```

Or something to that effect.
