### ISSUE TITLE
Event information missing

### ISSUE THREAD

**Issue by varunrau** [idehub/react-native-google-analytics-bridge#146]
Hi!

I've instrumented my app using this library and I can see my events flowing through to GA, but they seem to be missing the metadata I've added. Any idea why?

I initialize the tracker with something like this:

```
    var analytics = new GoogleAnalyticsTracker('CODE', {
      field: 1,
      otherfield: 2,
    });
```
and call it like this:
```
      analytics.trackScreenView('home', {field: 'hi'});

```

This is what I see on my dashboard:

![image](https://user-images.githubusercontent.com/1448222/27775861-c76a2a60-5f5a-11e7-8c48-e12cd625b368.png)

**Comment by cbrevik** [comment]
Hi @varunrau.

The [`trackScreenView`](https://github.com/idehub/react-native-google-analytics-bridge#trackscreenviewscreenname)-function does not allow for metadata to be sent with it.

Also the mapping you've done when constructing the [`GoogleAnalyticsTracker`](https://github.com/idehub/react-native-google-analytics-bridge#new-googleanalyticstrackertrackerid-customdimensionsfieldsindexmap--) is for `customDimensions` which is another set of functions, for example [`trackScreenViewWithCustomDimensionValues `](https://github.com/idehub/react-native-google-analytics-bridge#trackscreenviewwithcustomdimensionvaluesscreenname-dimensionindexvaluedict).

Also the GA view you're on is for events, not for tracked screens. So that's another reason why it is empty.

I'd recommend reviewing the [README](https://github.com/idehub/react-native-google-analytics-bridge#googleanalyticstracker-api) for the GoogleAnalyticsTracker API.
