### ISSUE TITLE
Flag to setLogLevel to verbose

### ISSUE THREAD

**Issue by pukhalski** [idehub/react-native-google-analytics-bridge#15]
Hey, is it any chance to wrap this feature as well?

I can turn on the dry run mode, but there's no possibility to check what's going on inside the lib itself.

**Comment by cbrevik** [comment]
Hi @pukhalski 

I have been considering making this available, but I am sort of torn. One of my requisites for features making it into this library is that it can be easily used cross-platform. I'd like the feature-parity to be as good as possible.

Therein lies the problem; on Android the LogLevel & Logger itself has been [deprecated](https://developers.google.com/android/reference/com/google/android/gms/analytics/Logger) in favor of using the [standard Android log system with logcat](https://developers.google.com/analytics/devguides/collection/android/v4/advanced#logger).
The iOS library instead relies on the GA Logger. 

I am considering implementing a solution for iOS, where this can be configured by a Info.plist setting, so that it does not impact the JS API.

**Comment by pukhalski** [comment]
It'd be nice to have. Also you can switch the logger behind the scenes - provide native for android and GA Logger for iOS, right?

Anyway, I need one of my two tickets to be resolved to actually use your library for production projects. 

Thank you so much for your work! Appreciate that!

**Comment by cbrevik** [comment]
Hi, because of the divergence between the platforms I decided to let this be configurable via the Info.plist.

You can add an item with the key `GAILogLevel ` and set the log level (a number) according to your needs; 

* 0: None
* 1: Errors
* 2: Warnings
* 3: Info
* 4: Verbose

**Comment by pukhalski** [comment]
Amazingly done! Thanks!
