### ISSUE TITLE
Google Analytics is not receiving data

### ISSUE THREAD

**Issue by IoanaBob** [idehub/react-native-google-analytics-bridge#151]
I installed the package and linked it correctly, and I don't receive any errors in my code. Versions are all good. I recreated the manual installation and everything was there. The tracker ID is correct and I am using it the same way as in the example. I put it in the constructor. Here is my code:

```
import {
  GoogleAnalyticsTracker,
  GoogleTagManager,
  GoogleAnalyticsSettings
} from 'react-native-google-analytics-bridge';

// The tracker must be constructed, and you can have multiple:

export default class ZApp extends Component {
  constructor() {
    super();
    this.state = {
      welcomed: false,
    };
    const tracker = new GoogleAnalyticsTracker('UA-xxxxxx-x');
    tracker.trackScreenView('ZApp');
    tracker.trackEvent('New Joiner', 'welcomed');
  }
```
Even though I don't get an error when I run the app, I get an error when I test the code:
"Cannot read property trackScreenView of undefined"

When I go into Google Analytics, I see this:
Tracking ID
UA-xxxxxx-x
Status
No data received in past 48 hours.

In the beginning, I thought it's because the account is new, but it's been almost a day already. Anyone has any idea what am I doing wrong?

Versions:
React native: 0.45.1
Google Analytics bridge: ^5.2.1
React: 16.0.0-alpha.12

**Comment by cbrevik** [comment]
Hi @IoanaBob 

It's kind of weird that you do not get an error while running the app, because `Cannot read property trackScreenView of undefined` means that either the constructed `GoogleAnalyticsTracker` is `undefined` or (more likely) the [underlying native bridge](https://github.com/idehub/react-native-google-analytics-bridge/blob/master/src/GoogleAnalyticsTracker.js#L56) is `undefined`. That should in theory either way throw an `Error` and stop execution.

Most likely fault is that something is still wrong with your installation of the library, and that is why the underlying native bridge is `undefined`. That error comes up [again and again](https://github.com/idehub/react-native-google-analytics-bridge/search?q=undefined&type=Issues), and nearly always it is because something failed with linking the library (https://github.com/idehub/react-native-google-analytics-bridge/issues/113#issuecomment-281263963).

I'd recommend debugging the JavaScript code with the Chrome debugger, to find out what exactly is `undefined`. And then review the installation again. Sometimes it's also a caching problem with your JavaScript, and resetting that helps (`yarn start -- --reset-cache` in project directory).

**Comment by IoanaBob** [comment]
I logged the "tracker" object, and this is what I get in response. To me, it seems like it exists, and the functions appear there. But why wouldn't it work when I call it?
![screen shot 2017-07-14 at 12 26 58](https://user-images.githubusercontent.com/15092862/28210580-013a1f82-6890-11e7-8d02-c9f02a2fb050.png)

**Comment by cbrevik** [comment]
I'd rather recommend attaching a remote debugger (Chrome), and stepping into the `trackScreenView` function call to see if the underlying native module is there. Even though the JavaScript-side of the tracker works, you still have to check if the underlying linked module is constructed.

**Comment by IoanaBob** [comment]
Thank you for the quick responses. I opened the debugger, and it worked for a while (around 30 minutes), but now it stopped. I tried to open the debugger again, and it still does not send. By the looks of it, it's not a problem with the library, if it ended up sending information. Any idea of other wrong settings I might have? thank you.

**Comment by RuiMRodrigues** [comment]
@IoanaBob did you solve this ?

**Comment by bryanberger** [comment]
@cbrevik scratching my head on this one. I tried to follow the readme with no success. I tried manually installing as listed here https://github.com/idehub/react-native-google-analytics-bridge/issues/113#issuecomment-281263963 still no success.

`Cannot read property 'trackEvent' of undefined` which is stating that the `GoogleAnayticsTracker` is undefined

**Comment by cbrevik** [comment]
Do you have a cod example @bryanberger? How are you using it?

I get a lot of this exact question, and 99% of the time it is either faulty installation/linking, or improper use of the `GoogleAnayticsTracker` class.

**Comment by bryanberger** [comment]
I ended up nuking the iOS project, cleaning everything and reinitializing it, and it worked. Great work on this btw, really appreciate it!

Out of curiosity, any reason why this would fail to work (even when all the packages appear to be linked in xcode via `react-native link` ?
