### ISSUE TITLE
Multiple GA tracking ids 

### ISSUE THREAD

**Issue by pukhalski** [idehub/react-native-google-analytics-bridge#16]
Any chance to make it work? My case: I want different GA tracking ids for development and production.

**Comment by cbrevik** [comment]
Just so I am not misunderstanding;

You want some way to switch between GA tracking ids for different builds, you're not looking to dynamically switch between them while running the same app build?

**Comment by pukhalski** [comment]
Yes. You are right. I need different tracking IDs for __DEV__ build and for release one.

**Comment by cbrevik** [comment]
Hi,

This seems like something that should be done by build configuration in your React Native project rather than solved by this library. For iOS it can be done with [user-defined variables](http://stackoverflow.com/a/18155637/5703116) combined with the GAITrackingId in Info.plist.

And for Android it can be done by for example checking if `BuildConfig.DEBUG` is true in your MainActivity.java where you add the `GoogleAnalyticsBridgePackage`. The Android side probably has something similar as far as build configuration goes with files as well.
