### ISSUE TITLE
Feature request: Possibility to configure tracking code in JS

### ISSUE THREAD

**Issue by sodik82** [idehub/react-native-google-analytics-bridge#19]
I would like to be able configure tracking code in JS part. It would have following benefits:

1. Less manual steps during installation and each RN upgrade.
2. Follow DRY principle - I have my tracking code in one place instead of two
3. The less I mess with native code the better - for persons like me that are not familiar with native development :)

It could be done as an alternative to current approach (not to break existing users). Possible solutions could be via static method like `GoogleAnalytics.setTrackingCode('UA-12345-1');` or any kind of constructor.

**Comment by cbrevik** [comment]
Hi! 

I am very much in agreement, but I see a few hurdles to overcome. 

At the moment the API just has fire-and-forget methods, which means there is no way of notifying the consumer that the tracker has not been created. The API could just swallow these exceptions, but that seems error-prone.

At least what needs to be solved (other than the `setTrackingCode` function):

* Checking in constructor/init if TrackerId is supplied from Info.plist/param. Only create if it is set.
* Checking in every tracker-call methods if tracker is created.
* Find some way to gracefully fail if tracker has not been created.

Discussion / PR would be welcome.

**Comment by sodik82** [comment]
What happens now if TrackerId is not supplied eg. in Info.plist?

**Comment by cbrevik** [comment]
At the moment the tracker is just set to `nil`. I have not seen this as a huge issue seeing as setting the GAITrackingId is part of the installation process.

**Comment by sodik82** [comment]
java/android codes is partly prepared for more trackers :) However each method of bridge would have to be extended by one new parameter. JS code would then maintain tracking ID or `undefined` in case when default/old way tracking ID should be used. 
In case when there would not be any tracking ID (old way or new way - most appropriate would be constructor) some nice exception could be thrown out of java - the check could be done in `getTracker` method for all use cases.

The new static method could forward the tracking ID to the bridge (the simplier method) or the constructor would create new instance keeping the tracking ID and provind it to bridge with each call (more complicated but more flexible - I could use more tracking ID). Not sure if this is the common use case. Which solution would you prefer?

It does not seems like a big problem to create PR for android part - but I won't be able to do it for iOS.

But first it would be good to come to some conclusion of which approach is the best.

**Comment by cbrevik** [comment]
Hi @sodik82, sorry for my tardiness in responding. I've been thinking about this issue the last day though.

A future feature I wanted to support is multiple trackers (which is why the Android implementation uses a HashMap-type to save Trackers by id). As such, it is not so silly to extend every Java-method with an extra parameter for `trackerId`.

As you could imagine though, this gives us a conundrum in how we structure the JS Code. If multiple trackers were to be supported, then we need to create a GoogleAnalytics (JS) instance for each tracker. But like I said, this is a future problem and not one I want to solve yet (YAGNI).

But, thinking about it in that perspective, I think letting the JS class maintain the `trackerId` is a good idea. The problem though is that at the moment the functions in the JS class are all `static`. 

In my opinion this is a good thing, as I feel the API is much easier to use if you do not have to pass the JS class instance around to all the places you want to call it. So, the best thing would be if the `trackerId` was set as a static property on the class.

As far as knowledge of if the trackerId is set natively or not:
I am wondering if we can just communicate that as a `bool` to the JS code. The Native bridge class (on both iOS and Android) has the ability to [export constants](https://github.com/facebook/react-native/blob/master/docs/NativeModulesIOS.md#exporting-constants) which the JS code can read.

In that case we would not have to throw an exception out of the Native-bridge and handle it gracefully, but rather handle that in the JS code.

So I think; as a first (non-breaking) implementation could be:
* Add a new static `setTrackerId` function
* Add a new static `trackerId` property
* Check in each JS tracking-function if NativeBridge-instance has a constant saying `trackingIdSetNatively: true`. If `false`, check if static `trackerId` property is set.
  * If neither is set, `throw Error`.
* Extend all native-methods with a `trackerId` parameter.
* Only send that parameter from JS if static `trackerId` is set.
* Retrieve `Tracker` natively from `HashMap` either from param or local private field.

Support for multiple trackers in JS, and sending in the trackerId through a class constructor can be a `v2.0` feature. At that point we can talk about making all tracking-functions non-static, and handling multiple JS GoogleAnalytics instances. :+1:

**Comment by sodik82** [comment]
If the multiple trackers are in plans, then it is good idea to extends function calls to NativeBridge. 

Not sure if "export constant" can work, but in worst case it can be exported as `boolean` function. However maybe I would suggest to check for error condition (neither JS nor native tracking ID) in native code as it can be done easily on one place (instead of in each JS tracking function).

Otherwise it suggested solutions seems good to me. And it won't be problem to extend JS to support non-static approach *in addition* to the convenient static way for simple usecases (only one tracking ID).

Something like 
```
GoogleAnalytics.trackEvent('testcategory', 'testaction'); // will send "null" tracking ID to native part where native tracking ID will be used

GoogleAnalytics.setTrackingId('AU-12345-2');
GoogleAnalytics.trackEvent('testcategory', 'testaction'); // will send "static" tracking ID from JS

const ga2 = new GoogleAnalytics('AU-12345-3');
ga2.trackEvent('testcategory', 'testaction'); // will send "instance" tracking ID from JS
```

**Comment by cbrevik** [comment]
We could do that, so the option here is to make a non-static function for every static function.

I do not agree that we need to handle this in native code though. An easier way would be to say that we **always** use the trackerId from the native-method parameters when retrieving the `Tracker` object in native code.

This could be accomplished by returning the `trackerId` exported as a constant from the NativeBridge. Next we'd either return that or an id set by `setTrackingId`. If neither is set, return `null`.

Then it's a matter of applying a sort of "middleware" to every static function in the `GoogleAnalytics` class type in JS.

```javascript
Object.getOwnPropertyNames(GoogleAnalytics)
.filter((name) => typeof GoogleAnalytics[name] === 'function')
.forEach((name) => {
  if (name === 'getTrackerId') return;
  var fn = GoogleAnalytics[name];
  
  GoogleAnalytics[name] = (...params) => {
    let trackerId = GoogleAnalytics.getTrackerId()
    if (trackerId == null)
      throw new Error("trackerId not set");
    fn.apply(this, params);
  }
})
```

Then we handle the `trackerId` not being set in JS or native in one place, that being just the middleware above. No nasty exceptions needing thrown from native code.

For the non-static methods we use the `trackerId` saved in the object-instance from the constructor `new GoogleAnalytics('AU-12345-3')`.

This would also require much less refactoring of native code, which I believe will not introduce as much complexity.

By the way I haven't been able to test the above code properly, wrote this in a hurry. Busy a lot this week.

**Comment by sodik82** [comment]
ok, we can make `trackerId` handling in JS code, it does not make big difference. In fact we don't need "middleware" at all. 
For now let's forget about non-static (instance) methods, those can be added later on without any special troubles.

The "standard" GA method can look like this (as we have spoken we want always provide tracking ID to native (bridge) code.
```
class GoogleAnalytics {
    static trackScreenView(screenName) {
        GoogleAnalyticsBridge.trackScreenView(getTrackerId(), screenName);
    }
...
}
```
and there will be private method that handles the logic about tracking ID (users don't need to get tracking ID - it is neither possible now)
```
let trackerId = GoogleAnalyticsBridge.getNativeTrackingId;

function getTrackerId() {
  if (!trackerId)
      throw new Error("TrackerId not set. See documentation for more detail how to setup GA");
  return trackerId
}

class GoogleAnalytics {
    static setTrackerId(tid) {
      // maybe throw exception if native tracker ID is set
      trackerId = tid;
  }
}
```

**Comment by cbrevik** [comment]
Haha, I guess I over-engineered a bit with the middleware :)

But then we're in agreement with how to proceed. Export any native set `trackerId` as constants by overriding the `getConstants` method:
```java
  @Override
  public Map<String, Object> getConstants() {
    final Map<String, Object> constants = new HashMap<>();
    constants.put("nativeTrackerId", _trackingId);
    return constants;
  }
```

Save it in a static property, and allow people to also set this same property via JS API. 

Next remove any use of `_trackingId` in the Java tracker-methods, extend the same methods with a `trackerId` parameter, and always use this parameter.

If you can handle the Android-implementation, I can implement the iOS-implementation. :+1:

**Comment by sodik82** [comment]
good :)

I will try to prepare android (and JS) implementation during the weekend, then you can review it and proceed with iOS implementation.

**Comment by sodik82** [comment]
hi there,

android part seems to work now. please check https://github.com/sodik82/react-native-google-analytics-bridge/commit/30a3a4024ed2cda8bed2df4995750aeb76aea51a

**Comment by cbrevik** [comment]
Cool, I did the iOS part this morning. I've made a PR based off of this.

I'll be testing it a bit more and probably merging in not too long.

**Comment by sodik82** [comment]
nice :+1:
