### ISSUE TITLE
GA not show screen name

### ISSUE THREAD

**Issue by luongs3** [idehub/react-native-google-analytics-bridge#213]
I follow your tutorial, everything seems ok, but screen name.
As you see image below, My application has one user visiting, but on Page View area. It has nothing.
[Google analytics real time overview](https://ibb.co/nNkZRw)
When i check Acquisition -> Channels -> direct, i can see 5 pages having title, and one doesn't have (not set)
[Google analytics aquisition](https://ibb.co/mRWDKG)

This is my code (on App.js file):
```
import {
  GoogleAnalyticsTracker,
  GoogleTagManager,
  GoogleAnalyticsSettings
} from 'react-native-google-analytics-bridge'
import Config from 'react-native-config'
let tracker = new GoogleAnalyticsTracker(Config.GOOGLE_ANALYTICS_TRACK_ID)
tracker.trackScreenView('Home')

function getCurrentRouteName(navigationState) {
  if (!navigationState) {
    return null
  }
  const route = navigationState.routes[navigationState.index]
  // dive into nested navigators

  if (route.routes) {
    return getCurrentRouteName(route)
  }
  return route.routeName
}

<RootNavigator
  onNavigationStateChange={(prevState, currentState) => {
    const currentScreen = getCurrentRouteName(currentState)
    const prevScreen = getCurrentRouteName(prevState)
    if (prevScreen !== currentScreen) {
      tracker.trackScreenView(currentScreen)
    }
  }}
  ref={(navigatorRef) => {
    NavigatorService.setContainer(navigatorRef)
  }}
/>
```

**Comment by cbrevik** [comment]
Hi @luongs3 

Have you stepped through the code of `getCurrentRouteName` and seen if it actually works?

I see you're trying to do some recursive calls there, and send in `route` instead of `navigationState`. Do these two objects have a similar structure?

**Comment by luongs3** [comment]
@cbrevik that function is working well. it returns exactly the name of Screen. 
I follow this tutorial https://reactnavigation.org/docs/guides/screen-tracking to apply your package with react navigation.
`route` and `navigationState` have difference structure

**Comment by cbrevik** [comment]
Well, I see in case `if (route.routes)` is evaluated as `true`, then it sends in route recursively (`getCurrentRouteName(route)`).

In that case it will try to eval `navigationState.routes[navigationState.index]`, where in reality `navigationState` is the newly sent in `route`. If it doesn't have a `.routes` prop or the newly eval'd route doesn't have a `routeName`, then it will track an empty screenName.

I am sorry I do not think this is an error with my library, especially since it works for every other screen.

Closing issue in that case.
