### ISSUE TITLE
Using GA in native code

### ISSUE THREAD

**Issue by 9mm** [idehub/react-native-google-analytics-bridge#24]
Hey, I noticed you switched to the JS API. I rely heavily on analytics and I'm always nervous that certain things get called twice or bugs introduced call things to re-render etc... I'm hesitant to put the tracking code in JS. I have a few questions

* Will passing it directly into the native code ever be deprecated? (I'm hoping not)
* If I did use JS, hypothetically, would calling the ID multiple times with the same value have any negative affect like double reporting or something?

Thanks!

**Comment by cbrevik** [comment]
Hi @9mm!

These are both good questions! 

**Short version**:

1. I have no plans on deprecating setting `trackerId` by native code. No worries!
2. At the moment the JS API module export is a class type (GoogleAnalytics) with a bunch of static tracker functions. The `trackerId` which these static functions uses is saved in a single static variable in JS. 
In other words, if you call the `setTrackerId` multiple times, all that happens is that you overwrite that same variable. In that sense, "multiple" trackers are not created, if that is your worry.

**Longer version**:
There is another open issue (#23), where one person is having problems with tracking with the latest version. I have not been able to reproduce his problems, but if you feel more safe setting `trackerId` by native code, you can keep on doing so!

The long term plan I have for this library **is** to support multiple trackers though. But in that case it would be in a non-static context, where people can have the option of constructing a new JS instance for tracking. For example:
```javascript
// Option A: Create new tracker with constructor:
var tracker = new GoogleAnalytics('UA-12345-1');
tracker.trackScreenView('Home');

// Option B: Just calling a static method on the type like we do now:
GoogleAnalytics.trackScreenView('Home');
```

In this use-case **Option B** will still support `trackerId` from native code, while **Option A** by design will not. I am just mentioning this because **Option A** would require more hand-holding, since it is up to the programmer to construct and handle the `GoogleAnalytics` instances, and in those cases it might lead to double reporting.

Hope this answers your questions!

**Comment by 9mm** [comment]
Thank you that was Amazing answer! We can close this, I can't because I'm on my phone

Thanks again

Sent from my iToaster

**Comment by cbrevik** [comment]
No problem!
