### ISSUE TITLE
Help me. build android failed

### ISSUE THREAD

**Issue by nguyenhatruong** [idehub/react-native-google-analytics-bridge#247]
![screen shot 2018-05-19 at 7 54 39 pm](https://user-images.githubusercontent.com/20810794/40268799-97a513da-5b9e-11e8-86a9-8ebda09c0114.png)

**Comment by nigharsh** [comment]
+1

**Comment by hasangilak** [comment]
+1

**Comment by cbrevik** [comment]
Hi guys, this should be fixed in `6.1.0` without any hacks needed.

See [release notes](https://github.com/idehub/react-native-google-analytics-bridge/releases/tag/v6.1.0) for more info.

Would be great if anyone could could confirm that it works for them using this version. 

**Important**: For those already on less than v6 of this library, there are some breaking changes when upgrading to v6+ (if you use ecommerce or custom dimensions). See [wiki post](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Version-6-breaking-changes) for more details.
