### ISSUE TITLE
Not able to track application crash.

### ISSUE THREAD

**Issue by aartisharma** [idehub/react-native-google-analytics-bridge#250]
I am not able to track uncaught exception(crashes) in the application.

> **tracker.setTrackUncaughtExceptions(true);**

I am using above line of code for tracking crashes.

Is there any additional settings or code which I am missing to track crashes?.  
as of now I am able to track ScreenView, Events, caughtExceptions.

**Comment by aartisharma** [comment]
I am able to track caught exceptions . But issue is with uncaught exception. I am not able to track  crash for both ios and android application on google analytics. Library has provided an API -

**setTrackUncaughtExceptions(Bool)**

But its not working

Thanks

**Comment by cbrevik** [comment]
Depends on which type of uncaught exception. If it happens natively before JavaScript-bundle is loaded, or before the module is loaded, then `setTrackUncaughtExceptions` is never run. Can you be more specific as to the cases where it is not tracked?

I ask because `trackUncaughtException` [is on by default](https://github.com/idehub/react-native-google-analytics-bridge/blob/b9a9168c54f09bd1b0941faf66f73b7c5c18ec4a/ios/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge.m#L21).

Also allow some time before data is visible, most of the data on GA is not "real time".
