### ISSUE TITLE
play-services version incompatible with react-native-push-notification

### ISSUE THREAD

**Issue by sirwoetang** [idehub/react-native-google-analytics-bridge#26]
With my app dependency being:

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-push-notification')
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

The Play-Services dependency within react-native-google-analytics-bridge is: 
dependencies {
    compile 'com.facebook.react:react-native:0.11.+'
    compile 'com.google.android.gms:play-services-analytics:8.+'
}

The Play-Services dependency within react-native-push-notification is: 
dependencies {
    ...
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
}

My builds fail with: 

Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzmu;

This can be worked around should you  manually change the dependency:
compile 'com.google.android.gms:play-services-analytics:8.+'
to:
compile 'com.google.android.gms:play-services-analytics:8.3.0'

Any idea how to do this without cloning the repo into my project?

**Comment by cbrevik** [comment]
Hi @sirwoetang!

This is a problem which I thought might show up again. If you look at issue #20, I was asked to upgrade to 8.4.0 since another library they were using also used 8.4.0 (while I used 8.3.0).

The reason I used `8.+` was so I would not have to update the dependency for every minor version of `play-services-analytics`. 

The other module `react-native-push-notification` should probably update to the latest (8.4.0) or add `8.+` like me.

But a solution you could try is adding the following in your `build.gradle`, before the other projects:
```gradle
compile("com.google.android.gms:play-services-analytics:8.3.0"){
    force = true
}
```

That should force the app to compile a the 8.3.0 version of the dependency my project uses.

So the dependencies in your `build.gradle` should be something like:
```gradle
    dependencies {
        compile fileTree(dir: "libs", include: ["*.jar"])
        compile("com.google.android.gms:play-services-analytics:8.3.0"){
            force = true
        }
        compile project(':react-native-google-analytics-bridge')
        compile project(':react-native-push-notification')
        compile "com.android.support:appcompat-v7:23.0.1"
        compile "com.facebook.react:react-native:+" // From node_modules
}
```

Can you try that and get back to me with the results?

**Comment by sirwoetang** [comment]
Hi @cbrevik, 

Your suggested changes worked like a charm. I had actually forked the repo to get it to work on my CI, which will not be necessary now. 

Thanks for the help!

**Comment by cbrevik** [comment]
Fantastic, glad to be of help!

**Comment by ospfranco** [comment]
Hey, I also got this dex error, on SafeParcelable package, I added:

```
compile("com.google.android.gms:play-services-analytics:8.3.0"){
    force = true
}
```

However now I get this:

`Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzjz;`

Any ideas con how to solve this?

**Comment by muganwas** [comment]
Saved my sanity, Weird thing is. this only happened to after my computer crashed and I had to reset my pc. Everything worked fine before.
