### ISSUE TITLE
Where to put tracking code?

### ISSUE THREAD

**Issue by Tom29** [idehub/react-native-google-analytics-bridge#271]
I've read all document but wonder where to put the tracking code for screen and event
```
tracker.trackScreenView("Home");
tracker.trackEvent("testcategory", "testaction");
```
Should i put them inside `constructor` or `render` method of component/screen?

**Comment by rishabh-saxena** [comment]
Hi @Tom29 !! You can put the `trackScreenView` in the componentDidMount lifecycle method of the component/screen and `trackEvent` in the onPress of the particular element whose click you are trying to track.
Hope that helps.

**Comment by cbrevik** [comment]
Hi, this question has been asked a few times (#66 #122).

It depends on how you structure your app. In general I recommend against putting it in `componentDidMount` since that is only ran when your component is mounted the first time. Not necessarily if you're navigating back to an already mounted component.
