### ISSUE TITLE
Library no longer implements requiresMainQueueSetup

### ISSUE THREAD

**Issue by nbolender** [idehub/react-native-google-analytics-bridge#275]
### Environment

(Which react-native version? What version of this library? iOS, Android, or both?)
react-native 0.56.0 / iOS 11 / react-native-google-analytics-bridge@6.0.0

### Steps to Reproduce

(Occurs on startup)

### Expected Behavior

No warning

### Actual Behavior

react-native warns:

> Module RCTGoogleAnalyticsBridge requires main queue setup ...

This is a reversion of #186

**Comment by cbrevik** [comment]
Thanks for reporting this @nbolender!

I removed `requiresMainQueueSetup` on purpose earlier because we don't use `constantsToExport` any longer. Apparently the same limitation extends to use of `init`. Will look into making the init code async later as well, but will quick-fix for now. Fixed in 1ebbe756d370ddd9a91ad7d9eb39b22793e2fa4d, and released as `6.0.1`.

**Comment by nbolender** [comment]
Thank you @cbrevik :)
