### ISSUE TITLE
Tracking of Non-interaction event possible?

### ISSUE THREAD

**Issue by bastiDomi** [idehub/react-native-google-analytics-bridge#279]
Hi,

is there any way to track an non-interaction event?

This feature was already implemented in the old version of react-native-google-analytis-bridge:
https://github.com/idehub/react-native-google-analytics-bridge/pull/178/files

But I dont find anything regarding it in the new docs.

Thanks!

**Comment by cbrevik** [comment]
Good catch @bastiDomi, this is an oversight. I was a bit unsure where to include non-interaction in the API surface, and sort of forgot to include it. I've kept that PR open as a reminder.

The problem is I am not sure if other kinds of hits than `trackEvent` support non-interaction (like `trackTiming` or whatever). From the native side it seems you can include it in all hit types. Which sort of points towards including it in `HitPayload` as a property. If it is just events though, then it probably makes sense to just include it in `trackEvent`. Bit unsure what the case is.

Anyway, PR is welcome. If not I'll fix this when I have some more time.

**Comment by cbrevik** [comment]
Looks like from protocol that it is "any" hit: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ni

So [`HitPayload`](https://github.com/idehub/react-native-google-analytics-bridge#hitpayload) then.
