### ISSUE TITLE
Failed to capture snapshot of input files for task ':app:preDebugBuild'

### ISSUE THREAD

**Issue by dumpsayamrat** [idehub/react-native-google-analytics-bridge#280]
I have installed react-native-google-analytics-bridge package into my project. Then I run `react-native run-android` to build the project and got the below error. 
```shell
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.2,16.0.2], [16.0.0,16.0.0]], but resolves to 16.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```

I really don't know how to fix this. I'm stuck with this problem for many hours.

### Environment
```
"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-firebase": "^4.3.8",
    "react-native-google-analytics-bridge": "^6.1.0"
  }
```

### Steps to Reproduce
1. react-native init <project_name>
2. install react-native-firebase 4.3.8 -> the app work fine.
3. install react-native-google-analytics-bridge -> can't build

### Code sample/demo project
android/build.gradle
```
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```

android/app/build.gradle
```
dependencies {
    compile project(':react-native-google-analytics-bridge')
    implementation project(':react-native-firebase')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.1"
}
// ...
apply plugin: 'com.google.gms.google-services'
```

**Comment by cbrevik** [comment]
Hi @dumpsayamrat!

Thanks for a great issue description, this allowed me to easily reproduce the issue. 

The `react-native-firebase` module depends on `firebase-core:16.0.1` and `play-services-base:15.0.1` (and a lot of others depending on how you use their module). While `react-native-google-analytics-bridge` depends on `play-services-analytics:+` and `play-services-tagmanager-v4-impl:+`, where `+` just mean "the latest".

The problem is as it says, different versions of underlying dependencies are being requested between these dependencies. A good place to check what these underlying dependencies are is at https://mvnrepository.com

For example, the site says that [firebase-core:16.0.1](https://mvnrepository.com/artifact/com.google.firebase/firebase-core/16.0.1) has [firebase-analytics:16.0.1](https://mvnrepository.com/artifact/com.google.firebase/firebase-analytics/16.0.1) and [firebase-measurement-connector-impl:16.0.1](https://mvnrepository.com/artifact/com.google.firebase/firebase-measurement-connector-impl/16.0.1) as dependencies (see **Compile Dependencies** further down on that page). These in turn depend on [play-services-measurement-base:16.0.0](https://mvnrepository.com/artifact/com.google.android.gms/play-services-measurement-base/16.0.0), which is the dependency being complained about.

Now [play-services-analytics:16.0.3](https://mvnrepository.com/artifact/com.google.android.gms/play-services-analytics/16.0.3) (which is the latest, remember `+`) depends on [play-services-measurement-base:16.0.2](https://mvnrepository.com/artifact/com.google.android.gms/play-services-measurement-base/16.0.2), which is where the trouble starts (16.0.0 vs 16.0.2).

So the solution here is to pin the `react-native-google-analytics-bridge` dependencies to a version which will match with `react-native-firebase`. So if we look at [play-services-analytics' versions](https://mvnrepository.com/artifact/com.google.android.gms/play-services-analytics/), we see that [play-services-analytics:16.0.1](https://mvnrepository.com/artifact/com.google.android.gms/play-services-analytics/16.0.1) depends on [play-services-measurement-base:16.0.0](https://mvnrepository.com/artifact/com.google.android.gms/play-services-measurement-base/16.0.0)

Pinning the version can be done in many ways. This module has implemented the same ability as a lot of other RN modules in the community, [by allowing the Play Services-version being set through `googlePlayServicesVersion` in the gradle script](https://github.com/idehub/react-native-google-analytics-bridge/blob/67c342a343e0930d57d1ade11eb3df9f2be42cb4/android/build.gradle#L25). This can be done as such in `<your-RN-app>/android/build.gradle`:
```gradle
buildscript {
    ext {
        googlePlayServicesVersion = "16.0.1"
        // ... rest of ext properties
    }
	// ... rest of gradle buildscript
}
```

The above will set `play-services-analytics` and `play-services-tagmanager-v4-impl` at `16.0.1`. And should fix the problem.

This will also do the same for other modules implementing `googlePlayServicesVersion`, like [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info/blob/2653ed6ac33de5bde423c3480af8fd24b385b9eb/android/build.gradle#L27).

Sometimes, Play Services will still mismatch even if you use `googlePlayServicesVersion`. For example, as you see [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info/blob/2653ed6ac33de5bde423c3480af8fd24b385b9eb/android/build.gradle#L30) depends upon [play-services-gcm](https://mvnrepository.com/artifact/com.google.android.gms/play-services-gcm), which has no `16.0.1` version (at the time of this writing).

In this case, instead of using `googlePlayServicesVersion`, you can also force dependencies resolution by adding a resolution strategy in your `<your-RN-app>/android/build.gradle`:
```gradle
allprojects {
    repositories {
        google()
		mavenLocal()
        // .. etc
        configurations.all {
            resolutionStrategy {
                // react-native-google-analytics-bridge
                force "com.google.android.gms:play-services-analytics:16.0.1"
                force "com.google.android.gms:play-services-tagmanager-v4-impl:16.0.1"
				// react-native-device-info
                force "com.google.android.gms:play-services-gcm:15.0.0"
            }
        }
    }
}
```

There are maybe other/better ways of doing this as well, but for compatibility with the rest of the RN modules in the community, this is the best way I've found so far of doing it. 

This comment got a bit longer than I intended, but I felt a proper issue description deserved a proper answer.

**Comment by dumpsayamrat** [comment]
Thank you very much. It works!!

 I really appreciate it.
