### ISSUE TITLE
Datalayer support

### ISSUE THREAD

**Issue by leenasn** [idehub/react-native-google-analytics-bridge#29]
Hi,

Thanks for the plugin. I was wondering whether it has support for TagManager's [Datalayer](https://developers.google.com/android/reference/com/google/android/gms/tagmanager/DataLayer). I couldn't see the same in the bridge yet. 

The TagManager also has [PreviewActivity](https://developers.google.com/android/reference/com/google/android/gms/tagmanager/PreviewActivity), to review the container settings before publishing the same. 

Any plans to add these to the bridge?

Thanks,
Leena

**Comment by cbrevik** [comment]
Hi @leenasn!

The bridge does not yet support Datalayer, but there is no reason for it not to. A PR here would be welcome.

I'm not sure how PreviewActivity would work for this bridge, since it seems to be different for iOS and Android. It might be better if at least for Android, it is something you add yourself to your own app manifest.
