### ISSUE TITLE
Best way to add event meta data?

### ISSUE THREAD

**Issue by vpfaulkner** [idehub/react-native-google-analytics-bridge#296]
I realize this is less of a technical question and more of a GA question but what is the best way to track/view event metadata? For example, we have a lot of custom settings and would like to track what settings are being changed the most and to what values. So for example, we have a setting called Brightness whose values are integers from 0-100.

I see that `trackEvent` accepts event metadata and a hit payload. However, event metadata appears to only allow for a single label which does not appear to be a fit. Perhaps we should use custom dimensions or custom metrics? So the command would be something like: `tracker.trackEvent(category, action, null, { customDimensions: properties })` and we could access the values (eg the Brightness values) from the screen below?

![image](https://user-images.githubusercontent.com/6223462/48208052-fc4ab780-e33f-11e8-9db2-5f6d373be1d7.png)

Thanks!

Vance

**Comment by cbrevik** [comment]
Hi @vpfaulkner!

I'll be honest and say I haven't had the need for similar metadata yet. But this seems like a job for custom dimensions/metrics. You can define them under the `Admin -> Property -> Custom Dimensions` section on Google Analytics. And then create Custom Reports under `Customization -> Custom Reports` which include the custom metadata and event hits.

This is more GA related, and I try to steer away from answering stuff like this because it's not really an issue with the library. So I am sorry but I'll have to close the issue :)

**Comment by vpfaulkner** [comment]
thanks for the direction @cbrevik, that's a big help.
