### ISSUE TITLE
Old linked version

### ISSUE THREAD

**Issue by 9mm** [idehub/react-native-google-analytics-bridge#3]
Hey, I noticed in the errors pane there is a warning that says...

    Object file libRCTGoogleAnalyticsBridge.a(RCTGoogleAnalyticsBridge.o)) was built for newer iOS version (8.2) than being linked (7.0)

I'm not sure how to fix this. Thanks!

**Comment by cbrevik** [comment]
Hey! I'm supposing it is because the target for your top level React Native project is iOS 7.0, whilst the Google Analytics Bridge is built for 8.2.

It is a warning, nothing serious, see [for example](http://stackoverflow.com/questions/31843900/xcode-7-warnings-object-file-was-built-for-newer-ios-version-than-being-linked).

A way to remove the warning is to go into your XCode-project ➜ Libraries ➜ RCTGoogleAnalyticsBridge.xcodeproj, and setting the iOS Deployment target to iOS 7.0 under the Build Settings. 

I might consider making iOS 7.0 the default deployment target for this native module.
