### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by 9mm** [idehub/react-native-google-analytics-bridge#30]
Is it possible to add this feature while still using your bridge?

https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#google-play-implement

Thanks!

**Comment by cbrevik** [comment]
Hi @9mm !

I've looked into campaigns briefly before, since I need it in one of my own apps. It looks like the iOS & Android implementation here differs a bit.

It seems to be possible to use automatic campaign attribution with iOS if you add the [iAd.framework](https://developers.google.com/analytics/devguides/collection/ios/v3/optional-features#idfa-files) to your project and allow IDFA (already possible with the bridge).
For Android it seems like maybe just modifying the `AndroidManifest.xml`.

If this is true, then it should work seamlessly next to my bridge. If it doesn't work automatically, then I probably need to modify the bridge in order to track campaign data along with normal events.

Again, I haven't tested this, so I am not sure how this would play out. I will look into this myself at one point, but at the moment I have other things I need to prioritize.

**Comment by 9mm** [comment]
Awesome, thanks for the reply. I'll let you know how it goes for future reference.

**Comment by ksarna** [comment]
Hey @9mm, did it work for you? I added `iAd.framework` as well as turned on IDFA collection but it seems it's still not working. Did you have to do something more?

**Comment by 9mm** [comment]
I roughly did what cbrevik said, and it seemed to work, although pretty much 100% of stuff related to ads is pure garbage code so it's kind of hard to tell.

**Comment by ksarna** [comment]
Ok, thanks for the reply. Couldn't agree more about quality of pretty much anything related with ads.

**Comment by master-atul** [comment]
Added this to my android manifest xml and it started working  for android

  ```
<!-- Used for Google Play Store Campaign Measurement-->
        <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver"
            android:enabled="true">
            <intent-filter>
                <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.AnalyticsService"
            android:enabled="true"
            android:exported="false"/>

        <!-- Optionally, register CampaignTrackingReceiver and CampaignTrackingService to enable
             installation campaign reporting -->
        <receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.CampaignTrackingService" />
```

**Comment by cbrevik** [comment]
We now have a function to track campain urls (6d4ba4fd48dcc0e2f6e1ad72f70055bc315d1621). So closing this issue. Please re-open if this doesn't cover the use-case.

**Comment by ylivsy** [comment]
Hey @cbrevik , I am trying to use react-native-google-analytics-bridge  to track campain urls. 
I am trying to sent Google Play link with parametrs and get the parameters in my app to know who sent the link.. Can you show any example of using react-native-google-analytics-bridge to gets this parameters? 
thank you a lot!

**Comment by krunalFlexiLoans** [comment]
@master-atul , can you please help me with it. I have added the plugin react-native-google-analytics-bridge & also have added the things mentioned by you in AndroidManifest.xml, now how can I track the utm_source in my app? What to write to track that this particular customer has come from a particular utm_source?

Please help.

**Comment by centaurreader** [comment]
i'm also trying to figure this out. does anyone have a working example?

**Comment by gerocha** [comment]
Hello, i'll tell how i've done my task here.

First i have created a file called CustomReceiver.java under 

> android/app/src/main/java/com/YOUR-APP/

here is a gist of the file that i wrote [customreceiver](https://gist.github.com/gerocha/27ef05e48238d1dcc3cc9b9463d01fbb)

after that you'll need to change your androidmanifest.xml, from:
`<receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
          android:exported="true">
          <intent-filter>
              <action android:name="com.android.vending.INSTALL_REFERRER" />
          </intent-filter>
</receiver>`

to 

`    <receiver android:name="com.<YOUR-APP>.CustomReceiver"
      android:enabled="true"
      android:exported="true">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
      </intent-filter>
    </receiver>
`

to test you should build your app a run it, after your app is open you should put in your console: 

`echo 'am broadcast \
    -a com.android.vending.INSTALL_REFERRER \
    -n "com.<YOUR-APP>/com.<YOUR-APP>.CustomReceiver" \
    --es "referrer" \
      "utm_source=test_source&utm_medium=test_medium&utm_term=test_term&utm_content=test_content&utm_campaign=test_name"; \
    exit' | adb shell`

if everything goes right you will see:

> Broadcasting: Intent { act=com.android.vending.INSTALL_REFERRER flg=0x400000 cmp=com.<YOUR-APP>/.CustomReceiver (has extras) }
> Broadcast completed: result=0

and under campaign -> source in google analytics console you will see your test_source, please note that i've put the tracker id in the customreceiver because i don't know how to recover it from the configuration file.

**Comment by gerocha** [comment]
build the code using this refs:

https://github.com/idehub/react-native-google-analytics-bridge/blob/master/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleAnalyticsBridge.java

https://stackoverflow.com/questions/27243146/android-using-google-analytics-v4-campaign-measurement

https://developers.google.com/analytics/devguides/collection/android/v4/campaigns

https://developers.google.com/analytics/solutions/testing-play-campaigns
