### ISSUE TITLE
Send data more frequently

### ISSUE THREAD

**Issue by hrlarsen** [idehub/react-native-google-analytics-bridge#4]
Hi

Currently it seems like the plugin is sending all data once every 30 seconds. Is there any way to increase this interval? Maybe send the event / screen as soon as it changes?

**Comment by cbrevik** [comment]
This is something that is on the [road map](https://github.com/idehub/react-native-google-analytics-bridge#roadmap) to make more configurable. 

To begin with I set that interval that high to conserve battery and network traffic. I believe the default is something like 2 minutes.

May I ask why you'd like to send events instantly?

**Comment by hrlarsen** [comment]
It's not that it is essential for my project, and should be more than fine to do it every 30 seconds. It was more out of curiosity, and this issue should just be marked as a suggestion. But I find it sufficient that it will be part of the 'more configureable' implementation.

But keep up the good work on this library, I find it very easy to use!

**Comment by cbrevik** [comment]
Thanks man, much appreciated!

**Comment by 9mm** [comment]
Does that mean if you visit a page and leave (even if its only 1 second, less than 30 seconds), that it's still tracked?

I'm looking at the realtime view and it seems very weird... it's like 1 out of 10 `trackScreenView`'s are getting tracked according to the name, but if I replace the GA call with a simple console log it's showing all of them perfectly.

I'm trying to basically just test that it's working and the realtime results are super weird.

**Comment by cbrevik** [comment]
Hi @9mm! 

The GA native library will collect all tracking-calls, and send them out as a batch every 20 seconds.
So, you shouldn't really lose any screen-tracking. But obviously, since it waits 20 seconds, this means that the realtime-view will always lag a little behind.

If the realtime view is important to you, you can edit the `dispatchInterval` in this file; https://github.com/idehub/react-native-google-analytics-bridge/blob/master/ios/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge.m#L22

I am also planning on making this configurable, but haven't really gotten around to it.
