### ISSUE TITLE
GoogleService-Info.plist Needed?

### ISSUE THREAD

**Issue by GantMan** [idehub/react-native-google-analytics-bridge#41]
When originally researching adding analytics, google suggests a configuration file:

https://developers.google.com/analytics/devguides/collection/ios/v3/#get-config

I don't see any reference to what to do with this file in your README, and I can't help but think this file is important.

**Comment by cbrevik** [comment]
Hi @GantMan!

That config file isn't necassery. In this library all such things are configured through native/JS code. 
This is done because I'd rather have people work with the Google Analytics library in a cross-platform way (through JS), rather than have to learn the ins-and-outs of the native side.

**Comment by GantMan** [comment]
Happy to hear it!  Just wanted to be sure :)
