### ISSUE TITLE
[QUESTION] Google Tag Manager - Full Implementation

### ISSUE THREAD

**Issue by xavierlefevre** [idehub/react-native-google-analytics-bridge#48]
Hello idehub,

First of all, thanks a lot for this great plugin, I decided to install it on my project, instead of native code we implemented months ago.
As an analytics lover, I think that the power of GTM is even greater than a traditional GA implementation. I wanted to know if you planned on going further with GTM, I would love to switch my implementation on this tool. And it seems that there is not a lot of good plugins out there.

Anyhow, thanks :)

Xavier

**Comment by cbrevik** [comment]
Hey @xavierlefevre!

Thanks for the kind words, good to hear that others find this module useful.

Most of the current implementation done by me has been based on my own needs. I do not do app development professionally, so my "needs" have been pretty much apps as hobby projects.

Limited time will probably keep me from giving this module all the attention it deserves, so I've been reliant on other contributers pitching in if they need a feature. I'll try to help any way I can with pull requests.

With regards to the GTM side of things, Datalayer support (#29) has already been requested. It seems like a simple enough feature for anyone to tackle. 

Are there any other specific features you would like to see implemented for GTM? It's better to break it down into single issues which people (you, me or others) can tackle, rather than "full implementation".

Again, if someone wants to pull request even the most simple features, I'll be more than happy to help out.

**PS.** 
One thing to note is that Google recently released [Firebase Analytics](https://analytics.googleblog.com/2016/05/introducing-firebase-analytics.html), which now seems to be the preferred way of implementing [GTM](https://developers.google.com/tag-manager/ios/v5/). In that regard it might be better to scope down feature requests to the essential, since the SDK used in this package is now considered "legacy".

**Comment by xavierlefevre** [comment]
@cbrevik  Pretty clear to me, I totally understand.
Depending on my needs and time, I might put my nose in all of that and contribute.

In the meantime, this works great and thanks again.

**Comment by mferranti** [comment]
hi @cbrevik , this package still using legacy sdk??

regards!

**Comment by cbrevik** [comment]
Yesm this package is not using Firebase @mferranti
