### ISSUE TITLE
GoogleAnalyticsBridge.nativeTrackerId is not an object

### ISSUE THREAD

**Issue by el-lsan** [idehub/react-native-google-analytics-bridge#59]
I'm getting the following error on the listed devices : 

iPad 2, iPad Retina, iPhone (5 and below)

![image](https://cloud.githubusercontent.com/assets/1249548/17669780/41a72952-630f-11e6-98e0-2df6efe05861.png)

however everything is fine on iPad Pro , iPad Air 2, iPad Air, iPhone (5s and above) 

```
dependencies:

"react": "15.2.1",
"react-native": "0.31.0",
"react-native-google-analytics": "^1.3.2",
"react-native-google-analytics-bridge": "^3.0.0",
```

**Comment by joselitojunior1** [comment]
Just got same error on Android

**Comment by cbrevik** [comment]
Are both of you using RN 0.31?

**Comment by jerolimov** [comment]
Maybe you missed to add the package in your MainApplication:

Add this import:

```
import com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridgePackage;
```

And update your getPackages implementation:

```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new GoogleAnalyticsBridgePackage() // add this line
      );
    }
```

**Comment by el-lsan** [comment]
@jerolimov Just double checked it, It's loaded for me and as I mentioned everything works as expected on : iPad Pro , iPad Air 2, iPad Air, iPhone (5s and above)

**Comment by cbrevik** [comment]
@el-lsan How are you testing it on those devices, through emulator?

Are you able to check which version of iOS those devices are running? Just to be sure; RN supports iOS 7.0 and above.

@joselitojunior1 Can you try @jerolimov's suggestion? For now, I'll assume your issue (on Android) is a different one than the iOS one.

**Comment by el-lsan** [comment]
@cbrevik I'm testing it on emulator and the IOS version on all devices that I listed is 9.3 (deployment target is IOS 8.0 and above)

**Comment by joselitojunior1** [comment]
@cbrevik it was a NPM/RNPM problem, afterall. Working fine on 0.31

thx

**Comment by krapspark** [comment]
I'm still getting the error with RN 0.31.
I tried `rnpm unlink` and `rnpm link` as well.
the error only shows when run through command line i.e. `react-native run-ios`.
runs fine when I run it through Xcode, though.

**Comment by devhyunjae** [comment]
Any clue? Works fine in iPhone, but having this problem in android

**Comment by krapspark** [comment]
I was able to solve it on my end. It was indeed `npm` or `rnpm` problem.

On the iOS end, our `package.json` was set up incorrectly so that we were missing peer dependencies for a third party package.

On the Android side, it turns out `rnpm` didn't fully install the module. After following through the manual installation process, we found places where the needed changes weren't made -- namely, the changes necessary in`MainApplication.java`.

Hope this is helpful for someone and sorry for the false alarm!

**Comment by robputer** [comment]
@krapspark - How did you fix the missing dependencies on iOS?

I am on 0.31.0 and am experiencing the same issues.  Similar to you, it runs fine when compiling through xcode.

**Comment by krapspark** [comment]
@robputer I noticed that there were warnings when i did a fresh `npm install`. i.e. `rm -rf node_modules` then `npm install`.

The warnings said something about missing peer dependencies.

The fix was setting the package versions in `package.json` to be pinned to the minor version (e.g. `"react": "~15.2.1"`) rather than major version (e.g. `"react": "^15.2.1"`)

**Comment by cbrevik** [comment]
Is this still a problem @el-lsan? I have been unable to replicate this.

Could you possibly provide a small sample project in which this happens? Does it happen with the example project in this repository?

**Comment by cbrevik** [comment]
Unable to reproduce, and issue seems to have gone stale. Closing for now.

**Comment by xareelee** [comment]
got the same error

![simulator screen shot oct 17 2016 22 07 47](https://cloud.githubusercontent.com/assets/804308/19440879/26326bae-94b6-11e6-9e2c-3916c5727318.png)


`yarn pacage.json`:

```js
    "react": "^15.3.0",  // 15.3.2
    "react-native": "^0.35.0",  // 0.35.0
    "react-native-google-analytics-bridge": "^3.1.0",  // 3.1.0
```

**Comment by xareelee** [comment]
OK, I found the problem.

The problem is I have multiple targets in my `.xcodeproj` and `react-native link react-native-google-analytics-bridge` will only do the job on one of targets. It made the native modules not be included.

To test whether your NativeModules is loaded, you may set a breakpoint in the `-init` method and launch the iOS app. It should stop at the breakpoint line when it initialized.

If not, please check your `.xcodeproj` -> `Build Phase` -> `Link Binary with Libraries` section. If there is no `libRCTGoogleAnalyticsBridge.a` on the list, follow the instruction [Manual installation iOS](https://github.com/idehub/react-native-google-analytics-bridge#manual-installation-ios) for setup.

**Comment by k3ithl1m** [comment]
Do we have to detach from Expo if we want to do a manual installation?
