### ISSUE TITLE
Setting custom dimensions/metrics without sending events or pageviews.

### ISSUE THREAD

**Issue by jstoeffler** [idehub/react-native-google-analytics-bridge#65]
Hi,

I've read the documentation, and it looks like custom dimensions can only be set while sending an event.

Is there a reason for this? I think it can be useful to have an API to set the custom dimension without sending an event (it should be sent in the next tracked events).

Also, I haven't seen an API for custom metrics, is this something you plan to implement?

Best

**Comment by cbrevik** [comment]
Hi @jstoeffler.

For iOS it seems like you can just set custom dimensions, and it will be sent along with any events or screen views you might send later. This is not the case for Android (as far as I can tell). The approach I've chosen with this module, is to provide complete feature parity on both platforms. 

This has both good and bad sides, of course. The overall goal here is to provide a JS API, which you can consume without having to understand the implementation details on either platform. So, that's why.

The time I can set aside to work on this module has been very limited as of late. So no plans to implement custom metrics. But, it is a pretty simple feature (very similar to custom dimensions), so a pull request here would be welcome.

**Comment by T-Spoon** [comment]
@cbrevik This looks to be the answer for Android: http://stackoverflow.com/a/31313028/1639040

If I have time I'll try and submit a PR for this.
