### ISSUE TITLE
Cannot read property 'nativeTrackerId of undefined'

### ISSUE THREAD

**Issue by Bobby-hewitt** [idehub/react-native-google-analytics-bridge#73]
I'm probably missing something really obvious but having performed an rnpm installed and linked the libraries as described, I am getting this message.  Looking at the code it looks like it can't find the native module Google Analytics Bridge.  If I knew more about xcode I could probs work this out myself. Unfortunately.... Any help would be appreciated!

**Comment by marcpechaitis** [comment]
@Bobby-hewitt,
I think its a problem with rnpm & the readme instructions.  I noticed that the MainActivity.java was updated, instead of MainApplication.java as the manual instructions say to do.

In my case here is what I did to resolve the same error for android:

Remove the line `import com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridgePackage;` from MainActivity.java

Add the line `import com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridgePackage;` to MainApplication.java

Add the line `new GoogleAnalyticsBridgePackage()` under `return Arrays.<ReactPackage>asList(` 

Step 4 of the manual instructions for Android says to update MainApplication.java, but the example shows the class MainActivity:

![screen shot 2016-10-13 at 7 16 18 pm](https://cloud.githubusercontent.com/assets/12177541/19372468/92cef13c-9179-11e6-8084-ee4f927c3e2e.png)


I'm on rn 0.30

**Comment by cbrevik** [comment]
Which version of RN are you using @Bobby-hewitt? 

I've also updated the README to reflect more recent changes in RN (with rnpm being migrated to `react-native link`).

**Comment by marcpechaitis** [comment]
@cbrevik, thanks for the update!...I noticed it Step 4 of Android manual steps still shows `public class MainActivity extends ReactActivity {`, is that inaccurate?

**Comment by cbrevik** [comment]
@marcpechaitis No, that's incorrect. I'll have it fixed!

**Comment by Ouadie** [comment]
If you end up here looking for a solution to `nativeTrackerId of undefined` for your tests, you can use https://github.com/CureApp/react-native-google-analytics-bridge-mock

**Comment by enguerranws** [comment]
FTR, faced the same issue, I just did the 5th of Manual Installation iOs of the readme (https://github.com/idehub/react-native-google-analytics-bridge#manual-installation-ios).

> Next you will have to link a few more SDK framework/libraries which are required by GA (if you do not already have them linked.) Under the same "Link Binary With Libraries", click the + and add the following:
> CoreData.framework
> SystemConfiguration.framework
> libz.tbd
> libsqlite3.0.tbd

**Comment by cbrevik** [comment]
In `v4.0.0` released yesterday, the tracker should be constructed instead of used statically:
`let tracker = new GoogleAnalyticsTracker('UA-12345-1');`. So use of `nativeTrackerId` and `setTrackerId` has been deprecated.

I think if you changed your code to instead to use the new `GoogleAnalyticsTracker` class, it will stop this from occurring.

See [v4.0.0 release notes](https://github.com/idehub/react-native-google-analytics-bridge/releases/tag/v4.0.0).

**Comment by dbuarque** [comment]
+1

**Comment by marlonbrgomes** [comment]
+1

**Comment by cbrevik** [comment]
+1 is really unhelpful. If you are having this problem I suggest looking at my previous comment, and tell me if that works.

**Comment by marlonbrgomes** [comment]
Im using the GoogleAnalyticsTracker class but isnt working on iOS yet, Android was always fine.

RN 0.36.0
RN-google-analytics-bridge 4.0.0

+ I did the manual installation for both (android/ios)

**Comment by cbrevik** [comment]
Can you show a small code example to reproduce the error @marlonbrgomes?

**Comment by ayercm** [comment]
@cbrevik thank you for your earlier answer, but I am using iOS and making the change you suggested did not change any behavior. I can comment out GA for now to keep making progress.

**Comment by cbrevik** [comment]
Aha, I see where the problem might be @ayercm. I'll take a look at this today

**Comment by cbrevik** [comment]
I've published a new version 4.0.2 @ayercm, can you test that version?

**Comment by ayercm** [comment]
Hi @cbrevik , I just had a chance to run a first test where I watched it fail, installed 4.0.2, and watched it pass, so yes this seems to have fixed it. I'll test 4.0.2 elsewhere but at the moment it looks great. Thanks for fixing:-)
