### ISSUE TITLE
Best way access APIs from native code

### ISSUE THREAD

**Issue by wilsonpage** [idehub/react-native-google-analytics-bridge#77]
Is it possible to send metrics from native code (java/swift)? For example in background tasks when the app is closed we'd like to be able to track activity.

**Comment by cbrevik** [comment]
There's not really a good way if you want to re-use the logic from the module. Not at the moment.

I'd recommend you do your own minor GA implementation if that is the case. I'm not even sure if the module can be guaranteed as "available" when the app is closed.

**Comment by wilsonpage** [comment]
Thanks. So you're suggesting using the GA SDK directly when recording metric from native code and not try to use the react-native-google-analytics-bridge?

**Comment by cbrevik** [comment]
Yes, just because of how the the module is architected, and how React exports the method you can call to the JS bridge. They're not really defined as callable methods from native code, at least not for Objective-C.

If you just need to record a few metrics it isn't that much code to do yourself. At least for Objective-C it's easy to access/create a tracker by trackerId and send a simple event: 
```objective-c
id<GAITracker> tracker = [[GAI sharedInstance] trackerWithTrackingId:trackerId];
NSString *category = @"somecategory";
NSString *action = @"someaction";
NSString *label = @"somelabel";
NSNumber *value = @50;
[tracker send:[[GAIDictionaryBuilder createEventWithCategory:category
                                                     action:action
                                                     label:label
                                                     value:value] build]];
```

For Java the tracker might need to be cached somehow (see [GoogleAnalyticsBridge.java](https://github.com/idehub/react-native-google-analytics-bridge/blob/master/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleAnalyticsBridge.java#L35). But still, not that much code.

**Comment by wilsonpage** [comment]
Thanks mate!
