### ISSUE TITLE
Unique users

### ISSUE THREAD

**Issue by tomelsner** [idehub/react-native-google-analytics-bridge#78]
This is more a question than an issue.... We've been using this plugin in our app and have been running an external beta test. Google analytics is reporting 170 users, but we know that we only have 30 beta testers. How does the plugin / google identify unique users? Is there something in the use that we should be doing to avoid app sessions counting as new users?

**Comment by cbrevik** [comment]
Hi @tomelsner, what are you looking at on the GA site? Sessions or users?

This module doesn't really do anything special wrt unique users, so that is up to the native GA library. But what you could do is use `setUser` and provide a unique ID if you want to make sure users are unique: https://developers.google.com/analytics/devguides/collection/ios/v3/user-id
